application: fitbitapi
version: 1
runtime: python
api_version: 1

default_expiration: "5d"

inbound_services:
  - warmup

handlers:
  - 
    url: /favicon.ico
    static_files: application/static/img/favicon.ico
    upload: application/static/img/favicon.ico
  - 
    url: /robots.txt
    static_files: application/static/robots.txt
    upload: application/static/robots.txt
  - 
    url: /static
    static_dir: application/static
  - 
    url: /
    static_files: application/static/index.html
    upload: application/static/index.html
  - 
    url: .*
    script: main.py

